### ISSUE TITLE
Check the images...

### ISSUE THREAD

**Issue by jn199** [rossturner/HTML5-ImageUploader#14]
Images aren't right.. You've got a [receipt for "Pasta a Basta" ](https://github.com/rossturner/HTML5-ImageUploader/blob/b6e42b53b076813d6e99ed9ecf271579e490f700/images/exif/IMG_7380.JPG) in there.

**Comment by rvalitov** [comment]
This is a correct image. Why do you think it's wrong?

**Comment by rossturner** [comment]
I agree, I don't understand this issue
