### ISSUE TITLE
EXIF is undefined error

### ISSUE THREAD

**Issue by datapharmer** [rossturner/HTML5-ImageUploader#9]
Tried running in chrome and edge via http://htmlpreview.github.io/?https://github.com/rossturner/HTML5-ImageUploader/blob/master/src/main/webapp/index.html and get message from console 

Uncaught ReferenceError: EXIF is not defined at HTMLImageElement.img.onload (<anonymous>:66:18)
![image](https://cloud.githubusercontent.com/assets/6548767/24916598/95b90998-1ea8-11e7-9ecd-075b5cce0344.png)

**Comment by rvalitov** [comment]
I suggest you to read the README first. There you can find about exif.js that you need to link first.

**Comment by datapharmer** [comment]
RTFM... got it. Sorry about that.
